export type ArtworkStatus = 'disponible' | 'vendu' | 'commande';

export type Artwork = {
  slug: string;
  imageId: string;
  extension: 'jpg' | 'jpeg' | 'png';
  title: string;
  format: string;
  status: ArtworkStatus;
  theme: keyof typeof themes;
  width: number;
  height: number;
  story: string;
  singularity?: string;
};

export const themes = {
  nature: 'Nature et fleurs',
  enfance: 'L’enfance',
  mer: 'La mer et les voyages',
  arts: 'La table, la musique, le cinéma',
  formes: 'Formes, miroirs et objets',
} as const;

export const artworks: Artwork[] = [
  {
    slug: 'envol-de-ballons',
    imageId: '7ee259d425f0442599bdb1f60605019c',
    extension: 'jpg',
    title: 'L’envol de ballons',
    format: '80 × 80 cm',
    status: 'vendu',
    theme: 'enfance',
    width: 315,
    height: 302,
    story:
      'Des ballons qui montent, chacun rempli d’un motif différent. Une des premières toiles carrées de grand format.',
  },
  {
    slug: 'feuilles-d-etain',
    imageId: '73136895b904448bbb96124e93dd7616',
    extension: 'png',
    title: 'Feuilles d’étain',
    format: '70 × 50 cm hors cadre',
    status: 'vendu',
    theme: 'formes',
    width: 315,
    height: 445,
    story: 'Des feuilles longues, dessinées en nervures d’étain, sur une toile verticale.',
  },
  {
    slug: 'music',
    imageId: 'ff7c00c371d64e6182bd34c04bf95e8d',
    extension: 'jpeg',
    title: 'Music',
    format: '80 × 80 cm hors cadre',
    status: 'vendu',
    theme: 'arts',
    width: 315,
    height: 313,
    story: 'Portées, clés, notes et cercles de vinyle : la musique traduite en motifs répétés.',
  },
  {
    slug: 'ovale-fleuri',
    imageId: '4a0011fe0ee54fa2a58b1665f2d2de06',
    extension: 'png',
    title: 'Ovale fleuri',
    format: 'Format à confirmer',
    status: 'vendu',
    theme: 'nature',
    width: 315,
    height: 265,
    story: 'Un ovale rempli de fleurs, le premier d’une série de deux.',
  },
  {
    slug: 'mandalas',
    imageId: 'b4c4690bf31f4edcb56cfd204d6c2580',
    extension: 'jpg',
    title: 'Mandalas',
    format: '120 × 40 cm hors cadre',
    status: 'disponible',
    theme: 'formes',
    width: 315,
    height: 130,
    story: 'Un format panoramique, trois mandalas côte à côte. La pièce la plus proche du Zentangle pur.',
  },
  {
    slug: 'fleur-eternelle',
    imageId: '907b1bdf4c2745c1bc7b7e5aa56e5ca0',
    extension: 'png',
    title: 'Fleur éternelle',
    format: '60 × 60 cm hors cadre',
    status: 'disponible',
    theme: 'nature',
    width: 315,
    height: 316,
    story: 'Une seule fleur, en couches de pétales, chaque couche avec son motif. Environ 150 heures.',
  },
  {
    slug: 'lotus',
    imageId: '4567d09e0fba454994626c56e3d90f12',
    extension: 'jpeg',
    title: 'Lotus',
    format: '50 × 50 cm hors cadre',
    status: 'vendu',
    theme: 'nature',
    width: 315,
    height: 322,
    story: 'Le lotus, symbole de patience : un motif par pétale.',
  },
  {
    slug: 'a-table',
    imageId: '84fed7b0e0234a4c82d42634b52388d9',
    extension: 'jpeg',
    title: 'À table !',
    format: '60 × 73 cm',
    status: 'vendu',
    theme: 'arts',
    width: 315,
    height: 383,
    story:
      'Couverts, casseroles et grains de café deviennent des tangles. Le premier tableau sur le thème de la cuisine.',
  },
  {
    slug: 'coeur-en-fete',
    imageId: 'a5de6742d7a344bc9141af36b57bee51',
    extension: 'jpeg',
    title: 'Cœur en fête',
    format: '60 × 73 cm hors cadre',
    status: 'disponible',
    theme: 'nature',
    width: 315,
    height: 379,
    story: 'Un cœur débordant de fleurs et de rubans, en hauteur.',
  },
  {
    slug: 'en-mer',
    imageId: 'eba99119bfb34aa49d11c5f0e26197b7',
    extension: 'png',
    title: 'En mer',
    format: '80 × 80 cm hors cadre',
    status: 'disponible',
    theme: 'mer',
    width: 315,
    height: 313,
    story: 'Vagues en écailles, bancs de poissons en points, une rose des vents.',
  },
  {
    slug: 'les-4-saisons',
    imageId: '94814d8a154b4200994e95f2e6be959e',
    extension: 'png',
    title: 'Les 4 saisons',
    format: 'Diamètre 110 cm, miroir 74 cm',
    status: 'disponible',
    theme: 'formes',
    width: 315,
    height: 303,
    story: 'Le printemps, l’été, l’automne et l’hiver autour d’un vrai miroir.',
    singularity: 'Un miroir de 74 cm entouré de quatre quartiers dessinés, dans un tour en fer forgé noir.',
  },
  {
    slug: 'attrape-coeur',
    imageId: '7382af884ff04770a4417122468760c1',
    extension: 'jpg',
    title: 'Attrape-cœur',
    format: '38 × 55 cm hors cadre',
    status: 'disponible',
    theme: 'formes',
    width: 315,
    height: 453,
    story: 'Un attrape-rêves en forme de cœur, plumes et perles dessinées.',
  },
  {
    slug: 'ovale-fleuri-2',
    imageId: 'd1052b2508a1454c851d318b8aa59fc3',
    extension: 'png',
    title: 'Ovale fleuri 2',
    format: '30 × 35 cm',
    status: 'vendu',
    theme: 'nature',
    width: 315,
    height: 264,
    story: 'Le second ovale, en petit format.',
  },
  {
    slug: 'les-myrtes',
    imageId: 'dad5c71942154b28b5b4e3f664405491',
    extension: 'jpg',
    title: 'Les myrtes',
    format: 'Toile 100 × 100 cm hors cadre',
    status: 'vendu',
    theme: 'nature',
    width: 315,
    height: 311,
    story:
      'Le plus grand format : un mètre sur un mètre, des branches de myrte en motifs serrés. Près de 200 heures.',
  },
  {
    slug: 'fossiles',
    imageId: '1ff91767be524dfd95147b34bee6bcc7',
    extension: 'jpg',
    title: 'Fossiles',
    format: '50 × 50 cm hors cadre',
    status: 'disponible',
    theme: 'formes',
    width: 315,
    height: 315,
    story:
      'Des fleurs dont les pétales ont quatre cents millions d’années. L’encre relie les fossiles entre eux.',
    singularity: 'Les pétales des fleurs sont de vrais fossiles d’orthoceras, collés sur la toile.',
  },
  {
    slug: 'envol-de-papillons',
    imageId: 'ef4311a39a094beb866707b4bbd18fa1',
    extension: 'png',
    title: 'Envol de papillons',
    format: 'Toile noire 60 × 73 cm, toile blanche 30 × 30 cm',
    status: 'disponible',
    theme: 'nature',
    width: 315,
    height: 380,
    story: 'Les papillons quittent la petite toile blanche pour la grande toile noire.',
    singularity: 'Les papillons sont en relief, collés sur la toile. Deux toiles se répondent.',
  },
  {
    slug: 'miroirs',
    imageId: 'fdbde0bb40724301b30425c3dd9c6747',
    extension: 'jpg',
    title: 'Miroirs',
    format: '60 × 60 cm hors cadre',
    status: 'vendu',
    theme: 'formes',
    width: 315,
    height: 314,
    story: 'On se voit dans le tableau : les cercles reflètent la pièce où il est accroché.',
    singularity: 'Les ronds sont de vrais miroirs, sertis dans le dessin.',
  },
  {
    slug: 'familles-de-papillons',
    imageId: 'fdbf7298102340679759a3d9401b74ce',
    extension: 'png',
    title: 'Familles de papillons',
    format: '40 × 40 cm hors cadre',
    status: 'disponible',
    theme: 'nature',
    width: 315,
    height: 311,
    story: 'Petits, moyens, grands : des papillons par familles, chaque aile avec son tangle.',
  },
  {
    slug: 'l-instant-fige',
    imageId: '535605455b78496da0f28a9b5ca9629e',
    extension: 'jpg',
    title: 'L’instant figé',
    format: '60 × 60 cm hors cadre',
    status: 'disponible',
    theme: 'formes',
    width: 315,
    height: 313,
    story: 'Le tableau fonctionne. Les aiguilles tournent sur un cadran de motifs.',
    singularity: 'Une véritable horloge customisée : elle donne l’heure.',
  },
  {
    slug: 'le-7e-art',
    imageId: '462187c0639141c185469dd7785ca2e2',
    extension: 'jpg',
    title: 'Le 7ᵉ art',
    format: '80 × 80 cm hors cadre',
    status: 'vendu',
    theme: 'arts',
    width: 315,
    height: 328,
    story: 'Clap, pellicule, projecteur : le cinéma en noir et blanc, forcément.',
  },
  {
    slug: 'reves-d-enfants',
    imageId: '03cd0a4e4b52411ea91b610307862a34',
    extension: 'png',
    title: 'Rêves d’enfants',
    format: '80 × 80 cm hors cadre',
    status: 'disponible',
    theme: 'enfance',
    width: 315,
    height: 316,
    story: 'Tout ce qu’un enfant dessine : lune, étoiles, fusée, animaux, en tangles.',
  },
  {
    slug: 'pancarte-chambre-d-enfant',
    imageId: '97f35ef6716b47c69e0c106a2c387dda',
    extension: 'png',
    title: 'Pancarte de chambre d’enfant',
    format: '20 × 20 cm',
    status: 'vendu',
    theme: 'enfance',
    width: 315,
    height: 341,
    story: 'Un petit format pour une porte de chambre.',
  },
  {
    slug: 'face-a-face',
    imageId: '37f5edfd86d148b387018cfc027bb39d',
    extension: 'jpg',
    title: 'Face à face',
    format: '60 × 30 cm hors cadre',
    status: 'disponible',
    theme: 'formes',
    width: 315,
    height: 178,
    story: 'Deux profils qui se regardent, un format allongé.',
  },
  {
    slug: 'l-envol-de-l-enfance',
    imageId: '8a51f6c8f6a84ef893a1c5932f5ee814',
    extension: 'jpg',
    title: 'L’envol de l’enfance',
    format: '60 × 60 cm hors cadre',
    status: 'disponible',
    theme: 'enfance',
    width: 315,
    height: 316,
    story: 'Un enfant, des ballons, et le vent dans les motifs.',
  },
  {
    slug: 'charlie',
    imageId: '0b3553ee3217477691c3a6a33d378959',
    extension: 'png',
    title: 'Charlie',
    format: 'Format à confirmer',
    status: 'commande',
    theme: 'enfance',
    width: 315,
    height: 399,
    story:
      'Commande pour un cadeau de naissance : le prénom structure le tableau, les tangles le remplissent.',
  },
];

export const statusLabels: Record<ArtworkStatus, string> = {
  disponible: 'Disponible',
  vendu: 'Collection privée',
  commande: 'Commande sur mesure',
};

export function artworkImage(artwork: Artwork, width = 1400) {
  const height = Math.round((artwork.height / artwork.width) * width);
  return `https://static.wixstatic.com/media/890b5a_${artwork.imageId}~mv2.${artwork.extension}/v1/fill/w_${width},h_${height},al_c,q_88/${artwork.slug}.${artwork.extension}`;
}

export function artworkBySlug(slug: string) {
  return artworks.find((artwork) => artwork.slug === slug);
}
